# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: digital_assets_market
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: digital_assets_market_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV['EXTERNAL_DATABASE_URL'] %>
  schema_search_path: "digital_assets_schema,public"

cable:
  adapter: postgresql
  url: <%= ENV['EXTERNAL_DATABASE_URL'] %>
  pool: 5

queue:
  adapter: postgresql
  url: <%= ENV['EXTERNAL_DATABASE_URL'] %>
  pool: 5

cache:
  adapter: postgresql
  url: <%= ENV['EXTERNAL_DATABASE_URL'] %>
  pool: 5
